networks:
  network:
    name: ${PROJECT_NAME}-network

services:
  zookeeper:
    container_name: ${PROJECT_NAME}-zookeeper
    image: confluentinc/cp-zookeeper:${ZOOKEEPER_VERSION}
    hostname: ${ZOOKEEPER_HOST}
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    expose:
      - ${ZOOKEEPER_CLIENT_PORT}
    networks:
      - network
    restart: ${RESTART_POLICY:-unless-stopped}
    cpus: ${ZOOKEEPER_CPUS:-0.000}
    mem_limit: ${ZOOKEEPER_MEM_LIMIT:-1G}
    mem_reservation: ${ZOOKEEPER_MEM_RESERVATION:-500M}

  kafka:
    container_name: ${PROJECT_NAME}-kafka
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    hostname: ${KAFKA_HOST}
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONNECTION_URL}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    expose:
      - ${KAFKA_PORT}
    depends_on:
      - zookeeper
    networks:
      - network
    restart: ${RESTART_POLICY:-unless-stopped}
    cpus: ${KAFKA_CPUS:-0.000}
    mem_limit: ${KAFKA_MEM_LIMIT:-1G}
    mem_reservation: ${KAFKA_MEM_RESERVATION:-500M}

  schema-registry:
    container_name: ${PROJECT_NAME}-schema-registry
    image: confluentinc/cp-schema-registry:${SCHEMA_REGISTRY_VERSION}
    hostname: ${SCHEMA_REGISTRY_HOST}
    environment:
      SCHEMA_REGISTRY_HOST_NAME: ${SCHEMA_REGISTRY_HOST}
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: ${ZOOKEEPER_CONNECTION_URL}
      SCHEMA_REGISTRY_LISTENERS: ${SCHEMA_REGISTRY_LISTENERS}
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: ${SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS}
      SCHEMA_REGISTRY_DEBUG: ${SCHEMA_REGISTRY_DEBUG}
    depends_on:
      - kafka
    expose:
      - ${SCHEMA_REGISTRY_PORT}
    networks:
      - network
    restart: ${RESTART_POLICY:-unless-stopped}
    cpus: ${SCHEMA_REGISTRY_CPUS:-0.000}
    mem_limit: ${SCHEMA_REGISTRY_MEM_LIMIT:-1G}
    mem_reservation: ${SCHEMA_REGISTRY_MEM_RESERVATION:-500M}

  producer:
    container_name: ${PROJECT_NAME}-producer
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: ${PRODUCER_TARGET}
      args:
        APP_DIR: producer
    env_file:
      - ./producer/.env
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    networks:
      - network
    restart: ${RESTART_POLICY:-unless-stopped}
    cpus: ${PRODUCER_CPUS:-0.000}
    mem_limit: ${PRODUCER_MEM_LIMIT:-1G}
    mem_reservation: ${PRODUCER_MEM_RESERVATION:-500M}

  consumer:
    container_name: ${PROJECT_NAME}-consumer
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: ${CONSUMER_TARGET}
      args:
        APP_DIR: consumer
    env_file:
      - ./consumer/.env
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    networks:
      - network
    restart: ${RESTART_POLICY:-unless-stopped}
    cpus: ${CONSUMER_CPUS:-0.000}
    mem_limit: ${CONSUMER_MEM_LIMIT:-1G}
    mem_reservation: ${CONSUMER_MEM_RESERVATION:-500M}
